# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Robert W. Gries"
description: "My projects and writings related to programming."
repository: "robert-w-gries/robert-w-gries.github.io"
url: "http://www.robert-w-gries.com" # the base hostname & protocol for your site, e.g. http://example.com

# Site owner
author:
  name: "Robert W. Gries"
  uri: &uri "http://robert-w-gries.com/about/"
  url: *uri
  #picture: "/assets/images/michael-rose-glitched.jpg"
  github: "robert-w-gries"

# Build settings
markdown: kramdown
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed

minimal_mistakes_skin: "contrast"

include: ["_pages"]

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
