# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Robert W. Gries"
description: "My thoughts and projects."
repository: "robert-w-gries/robert-w-gries.github.io"
url: "http://www.robert-w-gries.com"

# Site owner
author:
  avatar: "/assets/images/robert_gries_mt_rushmore.png"
  bio: "Software Engineer living in Research Triangle Park, North Carolina"
  github: "robert-w-gries"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed

minimal_mistakes_skin: "contrast"

paginate: 5 # amount of posts to show
paginate_path: /personal_blog/page:num/

include: ["_pages"]

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
      ads: false
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      ads: false

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
